// ── Top Companies for Competitor & App Node Autocomplete ───────
// Organized by category. ~100 per list, deduplicated at the bottom.

import type { ComboboxOption } from "./combobox";

// ── Top SaaS Companies ────────────────────────────────────────

const TOP_SAAS: string[] = [
  "Salesforce",
  "Microsoft 365",
  "Adobe Creative Cloud",
  "Shopify",
  "HubSpot",
  "Slack",
  "Zoom",
  "Atlassian",
  "ServiceNow",
  "Workday",
  "Snowflake",
  "Datadog",
  "Twilio",
  "Okta",
  "Cloudflare",
  "MongoDB",
  "DocuSign",
  "Zendesk",
  "Freshworks",
  "Notion",
  "Figma",
  "Canva",
  "Airtable",
  "Asana",
  "Monday.com",
  "ClickUp",
  "Linear",
  "Vercel",
  "Stripe",
  "Plaid",
  "Gusto",
  "Rippling",
  "Deel",
  "Brex",
  "Carta",
  "Toast",
  "Procore",
  "Veeva Systems",
  "Databricks",
  "Confluent",
  "Elastic",
  "Sumo Logic",
  "New Relic",
  "PagerDuty",
  "Amplitude",
  "Mixpanel",
  "Segment",
  "LaunchDarkly",
  "PostHog",
  "Sentry",
  "CircleCI",
  "GitLab",
  "GitHub",
  "Bitbucket",
  "Jira",
  "Confluence",
  "Trello",
  "Basecamp",
  "Intercom",
  "Drift",
  "Crisp",
  "Mailchimp",
  "SendGrid",
  "Postmark",
  "ConvertKit",
  "ActiveCampaign",
  "Klaviyo",
  "Loom",
  "Calendly",
  "Cal.com",
  "Typeform",
  "SurveyMonkey",
  "Grammarly",
  "1Password",
  "LastPass",
  "Dashlane",
  "Miro",
  "Lucidchart",
  "Whimsical",
  "Webflow",
  "Wix",
  "Squarespace",
  "WordPress.com",
  "Ghost",
  "Substack",
  "Medium",
  "Gumroad",
  "Lemon Squeezy",
  "Paddle",
  "Chargebee",
  "Recurly",
  "ProfitWell",
  "Baremetrics",
  "ChartMogul",
  "Dbt Labs",
  "Fivetran",
  "Airbyte",
  "Retool",
  "Supabase",
  "Zapier",
  "Fly.io",
  "Neon",
  "Render",
  "Dropbox",
  "Box",
];

// ── Top Influential & Groundbreaking Tech Companies ───────────

const TOP_TECH: string[] = [
  "Apple",
  "Google",
  "Amazon",
  "Microsoft",
  "Meta",
  "Tesla",
  "SpaceX",
  "NVIDIA",
  "Intel",
  "AMD",
  "Qualcomm",
  "Arm Holdings",
  "TSMC",
  "ASML",
  "Samsung",
  "Sony",
  "Nintendo",
  "IBM",
  "Oracle",
  "SAP",
  "Cisco",
  "Dell",
  "HP",
  "Lenovo",
  "Uber",
  "Lyft",
  "Airbnb",
  "DoorDash",
  "Instacart",
  "Netflix",
  "Spotify",
  "Disney+",
  "TikTok / ByteDance",
  "Snap",
  "Pinterest",
  "Reddit",
  "Twitter / X",
  "LinkedIn",
  "WhatsApp",
  "Telegram",
  "Signal",
  "Discord",
  "Twitch",
  "YouTube",
  "PayPal",
  "Visa",
  "Mastercard",
  "Coinbase",
  "Binance",
  "Robinhood",
  "Block (Square)",
  "Affirm",
  "Klarna",
  "Wise",
  "Revolut",
  "Nubank",
  "Grab",
  "Gojek",
  "Alibaba",
  "Tencent",
  "Baidu",
  "JD.com",
  "Xiaomi",
  "Huawei",
  "DJI",
  "BYD",
  "NIO",
  "Rivian",
  "Lucid Motors",
  "Waymo",
  "Cruise",
  "Boston Dynamics",
  "Palantir",
  "Anduril",
  "Blue Origin",
  "Rocket Lab",
  "Planet Labs",
  "Relativity Space",
  "Neuralink",
  "The Boring Company",
  "23andMe",
  "Illumina",
  "Moderna",
  "BioNTech",
  "CRISPR Therapeutics",
  "Unity",
  "Epic Games",
  "Roblox",
  "Valve",
  "Electronic Arts",
  "Activision Blizzard",
  "Riot Games",
  "CrowdStrike",
  "Palo Alto Networks",
  "Fortinet",
  "SentinelOne",
  "Zscaler",
  "Wiz",
  "HashiCorp",
  "Docker",
  "Red Hat",
  "Canonical",
];

// ── Top AI Companies ──────────────────────────────────────────

const TOP_AI: string[] = [
  "Anthropic",
  "OpenAI",
  "Google DeepMind",
  "Meta AI (FAIR)",
  "xAI",
  "Mistral AI",
  "Cohere",
  "AI21 Labs",
  "Inflection AI",
  "Character.AI",
  "Perplexity",
  "Stability AI",
  "Midjourney",
  "Runway",
  "Pika",
  "ElevenLabs",
  "Synthesia",
  "HeyGen",
  "Descript",
  "AssemblyAI",
  "Deepgram",
  "Hugging Face",
  "Weights & Biases",
  "Neptune.ai",
  "Comet ML",
  "LangChain",
  "LlamaIndex",
  "Pinecone",
  "Weaviate",
  "Chroma",
  "Qdrant",
  "Milvus / Zilliz",
  "Scale AI",
  "Labelbox",
  "Snorkel AI",
  "Cleanlab",
  "Jasper AI",
  "Copy.ai",
  "Writer",
  "Notion AI",
  "Grammarly AI",
  "GitHub Copilot",
  "Cursor",
  "Replit",
  "Tabnine",
  "Codeium",
  "Sourcegraph Cody",
  "Devin (Cognition)",
  "Adept AI",
  "Imbue",
  "Aleph Alpha",
  "Baichuan AI",
  "Zhipu AI",
  "01.AI",
  "Moonshot AI",
  "DeepSeek",
  "Minimax",
  "Suno",
  "Udio",
  "AIVA",
  "Luma AI",
  "Inworld AI",
  "Convai",
  "Reka AI",
  "Together AI",
  "Anyscale",
  "Modal",
  "Replicate",
  "Baseten",
  "BentoML",
  "Cerebras",
  "Groq",
  "SambaNova",
  "Graphcore",
  "Tenstorrent",
  "d-Matrix",
  "Rain AI",
  "Lepton AI",
  "Fireworks AI",
  "Fixie AI",
  "Relevance AI",
  "Vectara",
  "Glean",
  "Moveworks",
  "Forethought",
  "Ada Support",
  "Sierra AI",
  "Harvey AI",
  "Casetext (Thomson Reuters)",
  "EvenUp",
  "Hippocratic AI",
  "Abridge",
  "Viz.ai",
  "PathAI",
  "Recursion Pharmaceuticals",
  "Isomorphic Labs",
  "Poolside AI",
  "Magic AI",
  "Amazon Bedrock",
  "Google Vertex AI",
];

// ── Deduplicated & merged as ComboboxOption[] ─────────────────

function toOptions(names: string[]): ComboboxOption[] {
  return names.map((n) => ({ value: n, label: n }));
}

const allNames = new Set([...TOP_SAAS, ...TOP_TECH, ...TOP_AI]);
const sorted = [...allNames].sort((a, b) => a.localeCompare(b));

/** All companies merged, deduplicated, sorted A-Z. */
export const ALL_COMPANY_OPTIONS: ComboboxOption[] = toOptions(sorted);
